### PR TITLE
Колесов - Лабораторная работа #3

### PR DESCRIPTION
**Pull request by mk101**

### CODE REVIEW

**Review by TupoaMudille — CHANGES_REQUESTED** [review]
fix "Draft pull requests cannot be merged."

**Comment by mk101** [comment]
How can I fix this issue if the pull request is not ready. That's why it was marked as a [draft](https://github.blog/2019-02-14-introducing-draft-pull-requests/).

**Comment by TupoaMudille** [comment]
this is just a reminder for me
as soon as you finish the work, I will remove the issue
I understand that it is strange

**Comment by mk101** [comment]
@akandrin, @srselivan, запрашиваю ревью

**Review by TupoaMudille — APPROVED** [review]
ok

**Review by srselivan — APPROVED** [review]
👍

**Review by akandrin — APPROVED** [review]
Ок

**Pull request merged**
